//arithmetic operator
var a = 100; var b = 13; var c = 10; var linebreak = "<br>";
console.log("a + b + c = "); result = a + b + c;
console.log(result);
console.log(linebreak);
console.log("a + b = "); result = a + b;
console.log(result);
console.log(linebreak);
console.log("a - b = "); result = a - b;
console.log(result);
console.log(linebreak);
console.log("a / b = "); result = a / b;
console.log(result);
console.log(linebreak);
console.log("a % b = "); result = a % b;
console.log(result);
console.log(linebreak); 
//comparison operator
var a = 40; 
var b = 30; 
var linebreak = "<br />"; 
console.log("(a == b) => "); 
result = (a == b); 
console.log(result); 
console.log(linebreak); 
console.log("(a < b) => "); 
result = (a < b); 
console.log(result);
console.log(linebreak); 
console.log("(a > b) => "); 
result = (a > b); 
console.log(result); 
console.log(linebreak); 
console.log("(a != b) => "); 
result = (a != b); 
console.log(result); 
console.log(linebreak); 
console.log("(a >= b) => "); 
result = (a >= b); 
console.log(result); 
console.log(linebreak); 
console.log("(a <= b) => "); 
result = (a <= b); 
console.log(result); 
console.log(linebreak);
//assignment operator
var a = 100; 
var b = 50; 
var linebreak = "<br />"; 
console.log("Value of a => (a = b) => "); 
result = (a = b); 
console.log(result); 
console.log(linebreak); 
console.log("Value of a => (a += b) => "); 
result = (a += b); 
console.log(result); 
console.log(linebreak); 
console.log("Value of a => (a -= b) => "); 
result = (a -= b); document.write(result); 
console.log(linebreak); 
console.log("Value of a => (a *= b) => "); 
result = (a *= b); 
console.log(result); 
console.log(linebreak); 
console.log("Value of a => (a /= b) => "); 
result = (a /= b); 
console.log(result); 
console.log(linebreak); 
console.log("Value of a => (a %= b) => "); 
result = (a %= b); 
console.log(result); 
console.log(linebreak); 